name: Deploy Cloud Functions

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        service_account: 'my-ci-account@maimai-log.iam.gserviceaccount.com'
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Deploy Functions
      run: sh ci/deploy/deploy.sh
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
