name: Deploy Cloud Functions

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: maimai-log
        service_account_email: my-ci-account@maimai-log.iam.gserviceaccount.com
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy Functions
      run: sh ci/deploy/deploy.sh
